services:
    kibana:
        container_name: kibana-container
        image: docker.elastic.co/kibana/kibana:8.6.2
        volumes:
            - kibanadata:/usr/share/kibana/data
            # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - 5601:5601
        environment:
            - KIBANA_PASSWORD="abc12345678"
            - ELASTICSEARCH_HOSTS=http://localhost:9200
            - ELASTICSEARCH_URL=http://localhost:9200
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false

volumes:
    kibanadata:
        driver: local
